version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Victoria
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Victoria
    volumes:
      - ./overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    dns: 1.1.1.1
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./plex:/config
      - /mnt/media/tv:/tv
      - /mnt/media/movies:/movies
    restart: unless-stopped
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Victoria
      - WEBUI_PORT=8090
    volumes:
      - ./qbittorrent:/config
      - /mnt/media/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8090:8090
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Victoria
    volumes:
        - ./radarr:/config
        - /mnt/media/movies:/movies
        - /mnt/media/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Victoria
    volumes:
      - ./sonarr:/config
      - /mnt/media/tv:/tv
      - /mnt/media/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Victoria
    volumes:
      - ./lidarr:/config
      - /mnt/media/music:/music
      - /mnt/media/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Victoria
    volumes:
      - ./readarr:/config
      - /mnt/media/books:/books
      - /mnt/media/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped